### ISSUE TITLE
How do I switch the URLs in production?

### ISSUE THREAD

**Issue by jordanlambrecht** [aiji42/next-image-loader#141]
I have an aws s3 bucket setup that syncs with my local public/img folder so I can work with image assets locally and then have them served from s3 in production. My site is huge and I don't want to go back and manually switch out all the SRCs to use an env variable. However, I still want to use nextJS's image optimization. Would this work to do that?

**Comment by aiji42** [comment]
I don't know if it actually works correctly because I haven't tried it, but I'm sure your needs can be met with the settings below.

```js
// next.config.js
const withImageLoader = NODE_ENV === 'production' ? require('next-image-loader').withImageLoader : (conf) => conf

module.exports = withImageLoader({
  // write your next.js configuration values.
})
```

```js
// image-loader.config.js
import { imageLoader } from 'next-image-loader/image-loader'

imageLoader.loader = ({ src, width, quality }) => 
  `/_next/image?url=https://{YOUR_S3_BUCKET_DOMAIN}${src}&w=${width}&q=${quality}`
```

```tsx
<Image src="/example.png" alt="Picture of the author" width={500} height={500} />
```

**Comment by jordanlambrecht** [comment]
@aiji42 Thank you SO much dude! I've been banging my head on this for a week now. So the code you wrote works and changes the URLs successfully, but the response it gets back is a 400 bad request error: `"url" parameter is not allowed`. Any ideas?

**Comment by aiji42** [comment]
Set the domain of your S3 bucket to `images.domain` in next.config.js.
Next.js' image optimization process will only allow external resources if they are set in its domain list

https://nextjs.org/docs/api-reference/next/image#domains

**Comment by aiji42** [comment]
```

// next.config.js
const withImageLoader = process.env.NODE_ENV === 'production' ? require('next-image-loader').withImageLoader : (conf) => conf

module.exports = withImageLoader({
  images: {
    domains: ['YOUR_S3_DOMAIN']
  },
  // write your next.js configuration values.
})
```

**Comment by jordanlambrecht** [comment]
Okay two more questions:

1. It looks like nothing happens when I add the if statement to determine if it's production or not. It goes ahead and uses the production loader regardless.
2. I'm having issues with externally hosted images. It will try to append the Image Loader domain name to them so `https://othersite.com/img.jpg` becomes `https://mysite.com/https://othersite.com/img.jpg`

**Comment by aiji42** [comment]
Please share the code for `next.config.js` and `image-loader.config.js` and clearly explain where the problem is occurring.
