### ISSUE TITLE
custom image loader not being called in next 13.x

### ISSUE THREAD

**Issue by matteius** [aiji42/next-image-loader#142]
I just tried upgrading my saleor react-storefront to the latest version which is next 13.x but I found the custom image loader never even gets called.  I downgraded the pacckages.json to `12.3.3` and updated the imports of `next/legacy/image` to be `next/image` and the plugin resumed working.   I have been using this in tandem with next-compose-plugins since May.

**Comment by aiji42** [comment]
Can you give mo some more detailed information?
The library example is currently running on the latest Next.js (v13.0.4) and is working fine, no bugs found.
https://next-image-loader.vercel.app/
https://github.com/aiji42/next-image-loader/tree/main/example

**Comment by aiji42** [comment]
This is a natural result since we did not support `next/legacy/image` in next.js v13.
I just released v3.0.0 with `next/legacy/image` support. Please give it a try.

https://github.com/aiji42/next-image-loader/releases/tag/v3.0.0

**Comment by matteius** [comment]
Tried it out and the new version is working for this case.  Thanks for the quick turnaround!

**Comment by styfle** [comment]
Next.js 13 supports this feature natively, no plugin needed:

https://nextjs.org/docs/api-reference/next/image#loader-configuration

**Comment by aiji42** [comment]
@styfle Awesome! 
Thanks for letting me know. I was not aware of this document.  
It is finally time to seal this library!
